### ISSUE TITLE
License of MQTT for Tcl -> license for this repository?

### ISSUE THREAD

**Issue by stefan-muc** [efrecon/mqtt#2]
Previously _MQTT for Tcl_ didn't have any license, so it wasn't legally released to be used by others. [I got in contact with Schelte Brom](https://stackoverflow.com/questions/54235250/which-license-is-mqtt-for-tcl-released-under/54240854#54240854) and now he [released the code under BSD-3-Clause](https://chiselapp.com/user/schelte/repository/mqtt/vinfo?name=06ab27c2b0ad539a).

I don't know if it's allowed to release a BSD-3-Clause code under a BSD-2-Clause, so maybe this repository should switch license to match?

**Comment by efrecon** [comment]
Thanks for point this out. I think that they are more or less compatible, but to avoid any problems I have changed to BSD-3 Clause as of ecedf8d322cc48c43f1e73ee13f1f3463df71c14. I do not mind at all.
